server:
  port: 8081
spring:
  application:
    name: school
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml