CREATE TABLE IF NOT EXISTS CURSO
(
    CD_CURSO     SERIAL PRIMARY KEY,
    NM_CURSO     VARCHAR(100)    NOT NULL UNIQUE,
    DS_CURSO     VARCHAR(250) NOT NULL,
    TM_DURACAO   INTEGER,
    TS_INCLUSAO  TIMESTAMP    NOT NULL,
    TS_ALTERACAO TIMESTAMP
);

COMMENT ON TABLE CURSO IS 'TABELA DE REGISTRO DO CURSO.';
COMMENT ON COLUMN CURSO.CD_CURSO IS 'NÚMERO DE IDENTIFICAÇÃO DO CURSO.';
COMMENT ON COLUMN CURSO.NM_CURSO IS 'NOME DO CURSO.';
COMMENT ON COLUMN CURSO.TM_DURACAO IS 'DURAÇÃO DO CURSO EM ANOS.';
COMMENT ON COLUMN CURSO.TS_INCLUSAO IS 'DATA DE INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN CURSO.TS_ALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO DO REGISTRO.';


CREATE TABLE IF NOT EXISTS MATRICULA
(
    CD_MATRICULA SERIAL PRIMARY KEY,
    DT_MATRICULA DATE        NOT NULL,
    NM_STATUS    VARCHAR(10) NOT NULL,
    TS_INCLUSAO  TIMESTAMP   NOT NULL,
    TS_ALTERACAO TIMESTAMP
);

COMMENT ON TABLE MATRICULA IS 'TABELA DE REGISTRO DA MATRICULA.';
COMMENT ON COLUMN MATRICULA.CD_MATRICULA IS 'NÚMERO DE IDENTIFICAÇÃO DA MATRICULA.';
COMMENT ON COLUMN MATRICULA.NM_STATUS IS 'STATUS MATRICULA.';
COMMENT ON COLUMN MATRICULA.DT_MATRICULA IS 'DATA DA MATRICULA.';
COMMENT ON COLUMN MATRICULA.TS_INCLUSAO IS 'DATA DE INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN MATRICULA.TS_ALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO DO REGISTRO.';

CREATE TABLE IF NOT EXISTS MATRICULA_HAS_CURSO(
    CD_MATRICULA     INTEGER NOT NULL,
    CD_CURSO         INTEGER NOT NULL,
    CONSTRAINT FK_MATRICULA
        FOREIGN KEY (CD_MATRICULA)
            REFERENCES MATRICULA (CD_MATRICULA)
                ON DELETE SET NULL,
    CONSTRAINT FK_CURSO
        FOREIGN KEY (CD_CURSO)
            REFERENCES CURSO (CD_CURSO)
                ON DELETE SET NULL
);

COMMENT ON COLUMN MATRICULA_HAS_CURSO.CD_CURSO IS 'NÚMERO DE IDENTIFICAÇÃO DO CURSO.';
COMMENT ON COLUMN MATRICULA_HAS_CURSO.CD_MATRICULA IS 'NÚMERO DE IDENTIFICAÇÃO DA MATRICULA.';

ALTER TABLE ALUNO
    ADD COLUMN CD_MATRICULA INTEGER NOT NULL;
ALTER TABLE ALUNO
    ADD
        CONSTRAINT FK_ALUNO_MATRICULA FOREIGN KEY (CD_MATRICULA)
            REFERENCES MATRICULA (CD_MATRICULA)
            ON
                DELETE
                SET NULL;